<a href="https://colab.research.google.com/github/pritkudale/ML-for-Teachers/blob/main/Linear%20Regression/K_fold_cross_validation_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
# prompt: ignore worning
import warnings
warnings.filterwarnings('ignore')

In [51]:
# Import necessary library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [52]:
# Import dataset
df=pd.read_csv('https://raw.githubusercontent.com/pritkudale/ML-for-Teachers/refs/heads/main/Linear%20Regression/Admission_Predict.csv')
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [53]:
# prompt: drop serial no

df = df.drop('Serial No.', axis=1)
df.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [54]:
# Rename the 'Chance of Admit ' column
df = df.rename(columns={'Chance of Admit ': 'Chance of Admit'})

# Define features (X) and target (y)
X = df.drop('Chance of Admit', axis=1)
y = df['Chance of Admit']

In [55]:
# import train test split and Linear Regression

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [62]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Initialize and train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

print('Model test score is : ',model.score(X_test, y_test))

Model test score is :  0.8510865927629006


In [63]:
from sklearn.linear_model import Lasso

# Initialize and train the lasso regression model
model = Lasso()
model.fit(X_train, y_train)

print('Model test score is : ',model.score(X_test, y_test))

Model test score is :  0.2210295958574271


In [64]:
from sklearn.linear_model import Ridge

# Initialize and train the ridge regression model
model = Ridge()
model.fit(X_train, y_train)

print('Model test score is : ',model.score(X_test, y_test))

Model test score is :  0.8498854654848574


In [65]:
from sklearn.model_selection import KFold

# Initialize KFold
kf = KFold(n_splits=3) # Example:3 folds

for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [66]:
from sklearn.model_selection import train_test_split, KFold
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import r2_score  # Import r2_score


# Initialize KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42) # Example: 5 folds

# Initialize models
linear_model = LinearRegression()
lasso_model = Lasso()
ridge_model = Ridge()


# Function to perform k-fold cross-validation
def kfold_cv(model, X, y, kf):
  scores = []
  for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    scores.append(r2_score(y_test, y_pred))  # Use r2_score instead of mean_squared_error
  return np.mean(scores), np.std(scores)

# Perform k-fold cross-validation for each model
linear_r2, linear_std = kfold_cv(linear_model, X, y, kf)
lasso_r2, lasso_std = kfold_cv(lasso_model, X, y, kf)
ridge_r2, ridge_std = kfold_cv(ridge_model, X, y, kf)


print(f"Linear Regression - Average R^2: {linear_r2:.4f}, Standard Deviation: {linear_std:.4f}")
print(f"Lasso Regression - Average R^2: {lasso_r2:.4f}, Standard Deviation: {lasso_std:.4f}")
print(f"Ridge Regression - Average R^2: {ridge_r2:.4f}, Standard Deviation: {ridge_std:.4f}")

Linear Regression - Average R^2: 0.7893, Standard Deviation: 0.0507
Lasso Regression - Average R^2: 0.2553, Standard Deviation: 0.0290
Ridge Regression - Average R^2: 0.7894, Standard Deviation: 0.0514
